const assert=require('node:assert/strict'),fs=require('node:fs'),M=require('./stageplot-mics-v1.js'),D=require('node:vm').runInNewContext(fs.readFileSync('stageplot-drums-v12.js','utf8')+';createStageplotDrumModel()');
const clone=value=>JSON.parse(JSON.stringify(value));
assert.equal(new Set(M.catalog.map(m=>m.id)).size,M.catalog.length);
for(const query of ['sm57','SM 57','Shure sm-57'])assert.equal(M.search(query)[0].name,'Shure SM57');
assert.equal(M.search('m80 sh')[0].name,'Telefunken M80-SH');
assert(M.search('sE v kick').some(m=>m.name==='sE Electronics V KICK'));
assert(M.search('rode').some(m=>m.name==='RØDE NT5'));
assert(M.search('48v').every(m=>m.phantom));
assert.equal(M.lookup('Mein eigenes Mikrofon').name,'Mein eigenes Mikrofon');assert.equal(M.lookup('Mein eigenes Mikrofon').photo,'');
assert.equal(M.photo('Sennheiser MD 421'),'');assert.notEqual(M.photo('Telefunken M80'),M.photo('Telefunken M80-SH'));
const data=new Map(),storage={getItem:key=>data.get(key),setItem:(key,value)=>data.set(key,value)},prefs=M.preferences(storage);
prefs.toggle('Shure SM57');prefs.use('Audix D6');prefs.use('Shure SM57');prefs.use('Audix D6');
assert.deepEqual(M.preferences(storage).get(),{favorites:[M.find('Shure SM57').id],recent:[M.find('Audix D6').id,M.find('Shure SM57').id]});
prefs.toggle('Shure SM57');assert.equal(prefs.get().favorites.length,0);
for(const mic of M.catalog)prefs.use(mic.id);assert.equal(prefs.get().recent.length,12);
const blocked=M.preferences({getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}});assert.doesNotThrow(()=>{blocked.toggle('Shure SM57');blocked.use('Audix D6');});
const drums=D.drumDefaults(),object={id:'kit',type:'drums',drums},routing={inputs:[{id:'route1',sourceKey:'kit:drum-snare-up',number:17,instrument:'Meine Snare',microphone:'Audix i5',phantom:false,stagebox:'box',stageboxPort:5,notes:'Kein Gate',linkedSources:[]}],outputs:[],disabledSources:[]};
const before=clone({object,routing}),draft=M.hydrateDrums(drums,'kit',routing);
assert.equal(draft.mics['snare-up'].model,'Audix i5');assert.deepEqual(clone({object,routing}),before,'Opening or cancelling the editor never mutates saved data.');
draft.mics['snare-up']={enabled:true,model:'Neumann KM 184',phantom:true};
M.applyDrumChanges(routing,'kit',M.hydrateDrums(drums,'kit',routing),draft);
assert.deepEqual(routing.inputs[0],{...before.routing.inputs[0],microphone:'Neumann KM 184',phantom:true},'Drum selection updates only the selected signal’s mic fields.');
object.drums=D.normalizeDrums(draft);routing.inputs[0].microphone='Shure SM57';routing.inputs[0].phantom=false;
M.writeDrumRoute([object],routing.inputs[0],D.isDrums,D.normalizeDrums);
assert.equal(object.drums.mics['snare-up'].model,'Shure SM57');assert.equal(object.drums.mics['snare-up'].phantom,false);
const stable=clone({object,routing});M.writeDrumRoute([object],{...routing.inputs[0],adoptedSource:true,microphone:'Do not overwrite'},D.isDrums,D.normalizeDrums);assert.deepEqual(clone({object,routing}),stable);
const missing={id:'kit',type:'drums'};M.writeDrumRoute([missing],routing.inputs[0],D.isDrums,D.normalizeDrums);assert.equal(missing.drums.mics['snare-up'].model,'Shure SM57','Legacy drum objects without a stored config receive the current routing mic.');
const removed=clone(routing);removed.disabledSources=['kit:drum-snare-up'];removed.inputs=[];const disabled=M.hydrateDrums(object.drums,'kit',removed);assert.equal(disabled.mics['snare-up'].enabled,false);const reenabled=clone(disabled);reenabled.mics['snare-up'].enabled=true;M.applyDrumChanges(removed,'kit',disabled,reenabled);assert.deepEqual(removed.disabledSources,[]);
const blank=D.normalizeDrums({...drums,mics:{...drums.mics,'snare-up':{enabled:true,model:'',phantom:false}}});assert.equal(blank.mics['snare-up'].model,'','An explicitly cleared model must stay open, including after reload.');
assert(D.drumChannels('drums',blank).some(row=>row.id==='snare-up'),'Clearing a model keeps the signal.');
const html=fs.readFileSync('stageplot-studio.html','utf8');assert(html.indexOf('build-inline:start stageplot-mics-v1.js')<html.indexOf('build-inline:start stageplot-mic-picker-v1.js'),'The shared catalog is available before picker initialization.');
assert.match(html,/StageplotMics\.applyDrumChanges\(stage.routing/);assert.match(html,/StageplotMics\.writeDrumRoute\(objects/);assert.match(html,/StageplotMicPicker\.mount\(/);assert.match(html,/StageplotMicPicker\.open\(/);
console.log('PASS MICROPHONES: shared identities, original variants, tolerant instant search, persistent favorites/recents, blocked storage, two-way drum/audio changes, isolated drafts, metadata preservation and explicit clear/re-enable.');

const longName='Eigene Mikrofonkombination '+ 'x'.repeat(53);const legacy=D.normalizeDrums({...drums,mics:{...drums.mics,'snare-up':{enabled:true,model:longName,phantom:false}}});assert.equal(legacy.mics['snare-up'].model,longName,'Existing Audio model names up to 80 characters survive the Drum editor unchanged.');

// Added photos never merge model identities or confuse a newer revision with a legacy name.
assert(M.photo('Neumann KM 84'));assert.notEqual(M.photo('Neumann KM 84'),M.photo('Neumann KM 184'));
assert(M.photo('Beyerdynamic M201TG'));assert.notEqual(M.photo('Beyerdynamic M201TG'),M.photo('beyerdynamic M 201'));
assert(M.find('AKG C414 XLS/XLII').photoLabel.includes('C414 XLS'));
assert(M.find('Earthworks SR25mp').photoLabel.includes('Stereopaar'));
const missingPhotos=JSON.parse(fs.readFileSync('stageplot-assets/mics/missing-photos.json','utf8'));
assert.deepEqual(M.catalog.filter(m=>!m.photo).map(m=>m.name).sort(),missingPhotos.map(m=>m.model).sort());
assert(missingPhotos.every(m=>m.reason));
for(const m of M.catalog.filter(m=>m.brand==='Allgemein'))assert.equal(m.photo,'','Generic microphone types have no fictitious model photo.');
assert.match(fs.readFileSync('stageplot-mic-picker-v1.js','utf8'),/decoding="async"/);
