const assert = require('node:assert/strict');
const G = require('./stageplot-geometry-v1.js');
const near = (a,b,t=.015) => assert.ok(Math.abs(a-b)<t, `${a} != ${b}`);
const rect = (x,y,w,d) => [[x,y],[x+w,y],[x+w,y+d],[x,y+d]];
let g = G.legacy({w:8,d:5});
g.parts.push(G.part({id:'apron',shape:'segment',w:8,d:4,rise:4,y:5}));
let c = G.compile(G.normalize(g));
near(c.area,40+Math.PI*8); near(c.bounds.maxY,9,.002);
assert.equal(G.containsFootprint(c.floor,rect(3,6,2,1)),true);
assert.equal(G.containsFootprint(c.floor,rect(0,7,1,1)),false);
g=G.preset('t',8,5);c=G.compile(g);near(c.area,60);
assert.equal(G.containsFootprint(c.floor,rect(3.2,6,.5,1)),true);
assert.equal(G.containsFootprint(c.floor,rect(1,6,.5,1)),false);
g=G.legacy({w:8,d:5});g.parts.push(G.part({kind:'opening',x:3,y:2,w:2,d:2}));c=G.compile(g);
near(c.area,36);assert.equal(c.floor[0].length,2,'Innenring ist eine echte Öffnung.');
assert.equal(G.containsFootprint(c.floor,rect(2.5,1.5,3,3)),false,'Der Objektmittelpunkt allein reicht nicht.');
assert.equal(G.containsFootprint(c.floor,rect(0,0,2,2)),true);
g.parts.push(G.part({kind:'obstacle',x:.5,y:.5,w:1,d:1}));c=G.compile(g);near(c.area,36);near(c.usableArea,35);
assert.equal(G.containsFootprint(c.floor,rect(.5,.5,1,1)),true);assert.equal(G.containsFootprint(c.usable,rect(.5,.5,1,1)),false);
g=G.legacy({w:4.18,d:4.27});g.parts.push(G.part({x:-2,w:3,d:2}));c=G.compile(g);near(c.area,4.18*4.27+4,.001);near(c.bounds.minX,-2,.000001);
assert.deepEqual(G.normalize(G.copy(G.normalize(g))),G.normalize(g));assert.equal(g.parts[0].w,4.18);
g=G.preset('notch');c=G.compile(g);assert.equal(G.containsFootprint(c.floor,rect(7,4,.5,.5)),false);
for(const preset of ['round','circle','trapezoid','thrust','t','wings','l','u','notch','irregular']) assert.ok(G.compile(G.preset(preset)).area>0,preset);
assert.throws(()=>G.normalize({version:99,parts:[]}));
assert.throws(()=>G.normalize({...G.legacy({w:8,d:5}),parts:[G.part({shape:'polygon',points:[[0,0],[5,5],[0,5],[5,0]]})]}));
assert.throws(()=>G.normalize({...G.legacy({w:8,d:5}),parts:[G.part({w:Infinity})]}));
assert.throws(()=>G.normalize({...G.legacy({w:8,d:5}),parts:[G.part({id:'same'}),G.part({id:'same'})]}));
g=G.legacy({w:8,d:5});g.parts[0].shape='polygon';g.parts[0].points=[[0,0],[8,0],[8,5,-2],[0,5]];c=G.compile(G.normalize(g));near(c.bounds.maxY,7,.002);
const p=G.part({x:4,y:3,angle:37});const q=G.transform(p,[1.13,2.54]);const q2=G.inverse(p,q);near(q2[0],1.13,.00001);near(q2[1],2.54,.00001);
g=G.legacy({w:8,d:5});g.parts.push(G.part({id:'stair',kind:'stairs',w:1,d:1,anchor:{partId:'main-stage',edge:2,t:.5}}));G.syncAnchors(g);near(g.parts[1].x,3.5,.000001);near(g.parts[1].y,5,.000001);g.parts[0].d=6;G.syncAnchors(g);near(g.parts[1].y,6,.000001);
g=G.legacy({w:8,d:5});g.parts.push(G.part({id:'round-cut',kind:'opening',shape:'ellipse',x:3,y:1,w:2,d:2}));c=G.compile(G.normalize(g));
near(c.area,40-Math.PI);assert.equal(c.floor[0].length,2,'Kreisförmiger Ausschnitt ist ein echtes Loch.');
assert.equal(G.containsFootprint(c.floor,rect(3.9,1.9,.2,.2)),false);assert.equal(G.containsFootprint(c.floor,rect(3.02,1.02,.05,.05)),true,'Außerhalb des Kreises bleibt der Boden erhalten, auch innerhalb seiner Bounding Box.');
Object.assign(g.parts[1],G.resize(g.parts[1],3,1),{angle:30});c=G.compile(G.normalize(g));near(c.area,40-Math.PI*.75);
const ovalCenter=G.transform(g.parts[1],[1.5,.5]);assert.equal(G.containsFootprint(c.floor,rect(ovalCenter[0]-.1,ovalCenter[1]-.1,.2,.2)),false,'Ein gedrehtes Oval bleibt eine Bodenöffnung.');
console.log('PASS GEOMETRY: Rundungen, Vereinigung, Löcher, Ausschnitte, Hindernisse, präzise Maße, Anker und Validierung.');
