const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('stageplot-studio.html','utf8'),audio=fs.readFileSync('stageplot-audio-v1.js','utf8'),clone=value=>JSON.parse(JSON.stringify(value));
const extract=name=>{const match=html.match(new RegExp('  function '+name+'\\([^]*?\\n  }'));assert(match,name);return match[0];};
const fixture=(id,type,count=1)=>({id,type,label:id,io:{inputs:{count:0,connector:'XLR'},outputs:{count,connector:'XLR'},stereoPairs:count>=2?[1]:[],aliases:{inputs:[],outputs:[]}}});
const ctx={projectText:(value,max)=>String(value??'').slice(0,max),normalizeIoConnector:value=>value||'XLR',routeModes:new Set(['Mono','Stereo L','Stereo R','Mic','DI','Direct']),routeSignals:new Set(['Mic','Line','Instrument','Digital']),
 byId:{'keys-stage4':{category:'keys',instrument:true,short:'Keys',name:'Keyboard'},guitar:{instrument:true,category:'guitars',short:'Guitar'},amp:{instrument:true,category:'amps',short:'Amp'},mixer:{instrument:true,ioDefaults:{inputs:8,outputs:4}},wedge:{},rack:{}},
 drumModel:{isDrums:()=>false},objectIo:o=>o.io,ioAliasText:value=>value||'',objects:[fixture('keys','keys-stage4',4),fixture('guitar','guitar'),fixture('amp','amp'),fixture('mixer','mixer',4)],stage:{routing:{inputs:[],outputs:[]}},routeToken:()=>String(++ctx.token),token:0,queueDraftSave(){},say(){},reconcileCablesWithRouting(){},esc:value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;')};
ctx.routeSourceObject=row=>ctx.objects.find(o=>o.id===String(row?.sourceKey||'').split(':')[0]);ctx.routeSpec=(o,port,instrument,mode,signalType,extra)=>({sourceKey:o.id+':'+port,instrument,mode,signalType,...extra});ctx.ioAliasAt=()=>'';
vm.createContext(ctx);vm.runInContext(audio.slice(0,audio.indexOf("$('sp-audio-object').addEventListener")),ctx);
vm.runInContext(['normalizeRouteChannel','normalizeRouting','objectOutputPortKey','objectOutputBaseName','objectOutputSignal','generatedInputSpecs','generatedOutputSpecs','reconcileRouteList','syncRoutingFromStage'].map(extract).join('\n'),ctx);
ctx.syncRoutingFromStage(false,false);assert.equal(ctx.stage.routing.inputs.length,4,'New keyboards use two channels; mixer sockets do not become channels.');
assert.equal(ctx.stage.routing.inputs.filter(row=>row.sourceKey.startsWith('keys:')).length,2);const ids=ctx.stage.routing.inputs.map(row=>row.id);ctx.syncRoutingFromStage(false,false);assert.deepEqual(ctx.stage.routing.inputs.map(row=>row.id),ids,'Repeated reconciliation keeps IDs.');
let left=ctx.stage.routing.inputs[0];Object.assign(left,{edited:true,instrument:'Flügel L',number:17,stagebox:'box',stageboxPort:3,pickup:'DI',connector:'XLR',microphone:'J48',phantom:true,notes:'Unverändert'});ctx.syncRoutingFromStage(false,false);left=ctx.stage.routing.inputs[0];assert.equal(left.number,17);assert.equal(left.stageboxPort,3);assert.equal(left.instrument,'Flügel L');assert.equal(left.pickup,'DI');assert.equal(left.microphone,'J48');
ctx.stage.routing.disabledSources.push(ctx.stage.routing.inputs[1].sourceKey);ctx.stage.routing.inputs.splice(1,1);ctx.syncRoutingFromStage(false,false);assert.equal(ctx.stage.routing.inputs.length,3,'Deleted automatic signals stay disabled.');
const guitar=ctx.stage.routing.inputs.find(row=>row.sourceKey==='guitar:main'),amp=ctx.stage.routing.inputs.find(row=>row.sourceKey==='amp:cabinet');guitar.linkedSources=[amp];ctx.stage.routing.inputs=ctx.stage.routing.inputs.filter(row=>row.id!==amp.id);ctx.syncRoutingFromStage(false,false);assert.equal(ctx.stage.routing.inputs.length,2,'Merged source does not regenerate.');assert(ctx.audioObjectChannels(ctx.objects[2]).startsWith('CH '),'Member objects refer to the canonical channel.');
// Existing legacy four-output keyboards keep every channel and their metadata.
const legacy=ctx.generatedInputSpecs().filter(row=>row.sourceKey.startsWith('keys:')).map((row,i)=>({...row,id:'route-old-'+i,number:31+i,microphone:'Legacy '+i,stagebox:'old-box',stageboxPort:i+1}));ctx.stage.routing={inputs:legacy,outputs:[]};ctx.syncRoutingFromStage(false,false);assert.equal(ctx.stage.routing.inputs.filter(row=>row.sourceKey.startsWith('keys:')).length,4);assert.equal(ctx.stage.routing.inputs[3].number,34);
// Import / copy remaps source keys, stereo groups, patches, disabled sources and originals.
const migrated=ctx.normalizeRouting({inputs:[{...legacy[0],edited:true,adoptedSource:true,stereoGroup:'keys:stereo-out-1',linkedSources:[{...amp,number:55,notes:'Original behalten'}]}],outputs:[],disabledSources:['keys:out-4']},new Map([['keys','station-1'],['amp','station-2'],['old-box','station-3']]));assert.equal(migrated.inputs[0].adoptedSource,true);assert.equal(migrated.inputs[0].sourceKey,'station-1:out-1');assert.equal(migrated.inputs[0].stereoGroup,'station-1:stereo-out-1');assert.equal(migrated.inputs[0].stagebox,'station-3');assert.equal(migrated.inputs[0].linkedSources[0].sourceKey,'station-2:cabinet');assert.equal(migrated.inputs[0].linkedSources[0].number,55);assert.equal(migrated.disabledSources[0],'station-1:out-4');assert.deepEqual(clone(ctx.normalizeRouting(migrated)),clone(migrated));
const rows=[{id:'a',number:7,stereoGroup:'pair'},{id:'b',number:8,stereoGroup:'pair'},{id:'c',number:2},{id:'d',number:3}];const moved=ctx.moveAudioGroup(rows,'b','d','after');assert.deepEqual(clone(moved).map(row=>[row.id,row.number]),[['c',2],['d',3],['a',7],['b',8]]);
assert.deepEqual(clone(ctx.planAudioNumbers(rows,new Set(['a','b']),['#','#'])),[4,5]);assert.deepEqual(clone(ctx.planAudioNumbers(rows,new Set(['a','b']),['#','1'])),[4,1]);assert.deepEqual(clone(ctx.planAudioNumbers(rows,new Set(['a','b']),['7','8'])),[7,8]);assert.throws(()=>ctx.planAudioNumbers(rows,new Set(),['7']),/bereits/);
const boxes=[{id:'box',name:'A',capacity:4}],patchRows=[{id:'a',stagebox:'box',stageboxPort:1}];assert.deepEqual(clone(ctx.planAudioPorts(boxes,patchRows,new Set(),[{boxId:'box',port:''},{boxId:'box',port:2}])),[3,2]);assert.throws(()=>ctx.planAudioPorts(boxes,patchRows,new Set(),[{boxId:'box',port:1}]),/nicht frei/);
ctx.stage={routing:{inputs:[{number:7,instrument:'<Gitarre>',pickup:'DI',microphone:'J48',phantom:true,stagebox:'box',stageboxPort:3,notes:'Kabel stellt Band'}],outputs:[{number:2,instrument:'Monitor',outputKind:'monitor',mode:'Mono'}]}};ctx.stageboxRouteLocation=row=>row.stagebox?'Stagebox A IN '+row.stageboxPort:'Kein Stagebox-Patch';ctx.routeFrequency=()=>'';
const table=ctx.audioPrintTable('inputs');assert(table.includes('&lt;Gitarre>'));assert(table.includes('<td>48V</td>'));assert(table.includes('Stagebox A IN 3'));assert(!ctx.audioPrintTable('outputs').includes('IEM ·'));
assert(!html.includes('id="sp-iem-output-dialog"'),'Only one editor remains.');
console.log('PASS AUDIO: active signals, legacy migration, stable metadata, linked sources, stereo moves, explicit channel/port allocation and canonical print tables.');
