const assert=require('node:assert/strict'),fs=require('node:fs');
const S=require('./stageplot-share-v1.js');
const drums=require('node:vm').runInNewContext(fs.readFileSync('stageplot-drums-v12.js','utf8')+';createStageplotDrumModel()');
const document={stage:{title:'Testplan',projectId:'SP-TEST-123',w:8,d:6,project:{name:'Testplan',author:'PRIVATE',contacts:{foh:{name:'PRIVATE',contact:'PRIVATE'}},notes:'PRIVATE'},geometry:{version:1,notes:'PRIVATE',parts:[{id:'floor',w:8,d:6,note:'PRIVATE'}]},routing:{version:2,inputs:[{id:'route-1',number:12,instrument:'Keys',phantom:true,notes:'PRIVATE',linkedSources:[{id:'route-2',notes:'PRIVATE'}]}]}},objects:[{id:'one',type:'drums',x:1,y:2,angle:90,labelOffset:{x:-1.25,y:0.45,secret:'PRIVATE'},note:'PRIVATE',inventoryId:'PRIVATE',secret:'PRIVATE',drums:JSON.parse(JSON.stringify(drums.normalizeDrums({})))},{id:'two',type:'orchestra',orchestra:require('./stageplot-orchestra-v1.js')().preset()}],secret:'PRIVATE'};
const sharedDi={id:'di-shared',modelId:'radial-prod2',name:'Radial ProD2',channels:2,active:false,power:'none',phantom:false,objectId:'physical-di'};
const pickup={id:'guitar-di',sourceKey:'guitar:pickup-custom-7',origin:'pickup',acquisitionId:'take-custom-7',sourcePortKey:'out-1',sourceConnector:'Klinke',sourceSignalType:'Instrument',mode:'Mono',pickup:'DI',diDeviceId:'di-shared',diChannel:1,manual:true};
const monitor={id:'iem-left',sourceKey:'rack:in-1',mode:'Stereo L',stereoGroup:'rack:iem-1',iemGroup:'rack:iem-1',outputKind:'iem',monitorDeviceName:'PSM 900',monitorReceiverName:'Vocals',monitorAmplifierName:'',monitorDeviceKind:'iem',monitorActive:false};
document.stage.routing.devices=[{...sharedDi,notes:'PRIVATE',contacts:{owner:'PRIVATE'},inventoryId:'PRIVATE',secret:'PRIVATE'}];
document.stage.routing.inputs.push({...pickup,notes:'PRIVATE',linkedSources:[{...pickup,id:'original-di',notes:'PRIVATE',secret:'PRIVATE'}]}, {...pickup,id:'bass-di',sourceKey:'bass:out-1',diChannel:2}, {id:'cleared-di',sourceKey:'guitar:pickup-custom-8',diDeviceId:'',diChannel:null});
document.stage.routing.outputs=[{...monitor,notes:'PRIVATE',contacts:{artist:'PRIVATE'}},{...monitor,id:'iem-right',sourceKey:'rack:in-2',mode:'Stereo R'}];
const before=JSON.stringify(document),clean=S.clean(document);
assert.equal(JSON.stringify(document),before);assert.ok(!JSON.stringify(clean).includes('PRIVATE'));
assert.deepEqual(clean.objects[0].labelOffset,{x:-1.25,y:0.45});
assert.deepEqual(clean.objects[0].drums,document.objects[0].drums);
assert.deepEqual(clean.objects[1].orchestra,document.objects[1].orchestra);
assert.equal(clean.stage.routing.inputs[0].number,12);assert.equal(clean.stage.routing.inputs[0].phantom,true);
assert.deepEqual(clean.stage.routing.devices,[sharedDi]);
assert.deepEqual(clean.stage.routing.inputs[1],{...pickup,linkedSources:[{...pickup,id:'original-di'}]});
assert.deepEqual(clean.stage.routing.inputs.slice(1,3).map(row=>[row.mode,row.diDeviceId,row.diChannel]),[['Mono','di-shared',1],['Mono','di-shared',2]],'Two mono sources preserve independent ports on one physical stereo DI.');
assert.equal(Object.hasOwn(clean.stage.routing.inputs[0],'diDeviceId'),false,'Legacy absence must stay distinct from an explicitly cleared DI.');
assert.deepEqual(clean.stage.routing.inputs[3],{id:'cleared-di',sourceKey:'guitar:pickup-custom-8',diDeviceId:'',diChannel:null});
assert.deepEqual(clean.stage.routing.outputs[0],monitor);
assert.deepEqual(S.clean(clean),clean,'Sharing twice does not change source or device identities.');
const malformed=S.clean({stage:{routing:{devices:[{...sharedDi,name:{secret:'PRIVATE'},channels:['PRIVATE'],extra:'PRIVATE'}],inputs:[{diDeviceId:{secret:'PRIVATE'}}]}}});
assert.equal(malformed.stage.routing.devices[0].name,null);assert.equal(malformed.stage.routing.devices[0].channels,null);assert.equal(malformed.stage.routing.inputs[0].diDeviceId,null);assert.ok(!JSON.stringify(malformed).includes('PRIVATE'));
const sql=fs.readFileSync('supabase/migrations/0008_routing_devices.sql','utf8'),schema=sql.match(/share-schema:start[^\n]*\n\s*'([^']+)'::jsonb/)[1];assert.deepEqual(JSON.parse(schema),S.schema,'Client and server must enforce the same allowlist.');
for(const value of ['sp-test-123','  SP-TEST-123  ','https://example.org/#p/SP-TEST-123','#p/SP-TEST-123'])assert.equal(S.projectId(value),'SP-TEST-123');
for(const value of ['SP-','hello','https://example.org/?id=SP-X','#p/%ZZ','SP-X\nY','SP-'+'X'.repeat(80)])assert.equal(S.projectId(value),'');
const config={url:'https://stageplot-qa.supabase.co',publishableKey:'sb_publishable_test'},requests=[];
assert.equal(S.configured(config),true);assert.equal(S.configured({...config,publishableKey:'sb_secret_private'}),false);
(async()=>{
 const client=S.create({config,token:async()=>'test-token',fetch:async(url,init)=>{requests.push({url,init});return {ok:true,json:async()=>url.endsWith('_get')?{project_id:'SP-TEST-123',document}: {active:true}};}});
 await client.publish(document);let request=requests.at(-1);assert.ok(!request.init.body.includes('PRIVATE'));assert.equal(request.init.headers.Authorization,'Bearer test-token');assert.equal(request.init.cache,'no-store');
 const received=await client.get('sp-test-123');assert.ok(!JSON.stringify(received).includes('PRIVATE'));assert.equal(requests.at(-1).init.headers.Authorization,undefined);
 await S.create({config,fetch:async(_url,init)=>{assert.equal(init.headers.Authorization,undefined);return {ok:true,json:async()=>({active:false,owned:false,available:true})};}}).status('SP-TEST-123');
 await client.revoke('SP-TEST-123');assert.equal(JSON.parse(requests.at(-1).init.body).p_project_id,'SP-TEST-123');
 await assert.rejects(S.create({config,fetch:()=>{throw Error('must not fetch');}}).publish(document),/Berechtigung/);
 await assert.rejects(S.create({config:{},fetch:()=>{throw Error('must not fetch');}}).get('SP-TEST-123'),/nicht eingerichtet/);
 for(const [response,pattern] of [[{ok:true,json:async()=>null},/widerrufen/],[{ok:false,status:404,json:async()=>({})},/nicht eingerichtet/],[{ok:false,status:400,json:async()=>({message:'NOT_OWNER'})},/vergeben/],[{ok:false,status:400,json:async()=>({message:'SHARE_LIMIT'})},/100/],[{ok:true,json:async()=>({project_id:'SP-WRONG',document})},/falsche/]]){
  await assert.rejects(S.create({config,fetch:async()=>response}).get('SP-TEST-123'),pattern);
 }
 const abort=S.create({config,timeout:5,fetch:async(_url,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('timeout'),{name:'AbortError'}))))});
 await assert.rejects(abort.get('SP-TEST-123'),/antwortet nicht/);
 console.log('PASS SHARE: immutable client/server allowlist, complex instruments, ID parsing, authenticated writes, anonymous reads and errors.');
})().catch(error=>{console.error(error);process.exitCode=1;});
